### ISSUE TITLE
PageUp does nothing

### ISSUE THREAD

**Issue by baturinsky** [gagiopapinni/Back-And-Forth#1]
Seriously, why use that key for jumping? I tried your game in browser (Firefox), pressing PageUp in any imaginable way, no effect. Space works though.

**Comment by gagiopapinni** [comment]
seems to be this https://github.com/gagiopapinni/Back-And-Forth/commit/b83025789ef4c4d8c0dfc90999bff855b963ca54 is the case. I just wrongly referred to ArrowUp button as PageUp. Thanks.

**Comment by gagiopapinni** [comment]
@baturinsky  seems to be this https://github.com/gagiopapinni/Back-And-Forth/commit/b83025789ef4c4d8c0dfc90999bff855b963ca54 is the case. I just wrongly referred to ArrowUp button as PageUp. Thanks.
